name: Checks

on:
  push:
    branches:
      - dev
      - pprod
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.19.0'

      - name: Enable yarn 1
        run: corepack enable && corepack prepare yarn@1.22.22 --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Types, lint, format
        run: yarn check-all

      - name: Tests
        run: yarn test

      - name: Build
        run: yarn build
